---
header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: "Patrick J. Scruggs"
    first-publication-year: &fp_year "2025"
    copyright-year: "2025-2026"
    software-name: "slogcp-pubsub"

  paths:
    - '**/*.go'
    - '**/*.js'
    - '**/*.ts'
    - '**/*.java'
    - '**/*.py'
    - '**/*.sh'
    - '.github/scripts/**/*.py'

  paths-ignore:
    - 'dist'
    - 'vendor'
    - 'node_modules'
    - '**/*.md'
    - '**/*.yml'
    - '**/*.yaml'
    - 'LICENSE'
    - 'go.mod'
    - 'go.sum'
    - '.gitignore'

  comment: on-failure

  license-location-threshold: 1000
